platform :ios,'9.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'IAPDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'RMStore'
  pod 'AFNetworking','~>3.2.1'
  pod 'YYModel'

  # Pods for IAPDemo

  target 'IAPDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IAPDemoUITests' do
    # Pods for testing
  end

end
